In [22]:
# Utilizing the Matrix Multiplication for calculating the cosine similarities between people

In [ ]:
import numpy as np
M = np.array([ # Three people and four movies rating 
    [.1, .2, .4],
    [.2, .2, .3],
    [.3, .2, .1],
    [.1, .2, .1],
])

In [8]:
sqM = np.square(M)
print(sqM)
norms = np.sqrt(sqM.sum(axis=0))
norms

[[0.01 0.04 0.16]
 [0.04 0.04 0.09]
 [0.09 0.04 0.01]
 [0.01 0.04 0.01]]


array([0.38729833, 0.4       , 0.51961524])

In [14]:
uM = M / norms

In [17]:
uM

array([[0.25819889, 0.5       , 0.76980036],
       [0.51639778, 0.5       , 0.57735027],
       [0.77459667, 0.5       , 0.19245009],
       [0.25819889, 0.5       , 0.19245009]])

In [20]:
umT = uM.T
umT

array([[0.25819889, 0.51639778, 0.77459667, 0.25819889],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.76980036, 0.57735027, 0.19245009, 0.19245009]])

In [21]:
umT @ uM

array([[1.        , 0.90369611, 0.69566559],
       [0.90369611, 1.        , 0.8660254 ],
       [0.69566559, 0.8660254 , 1.        ]])

In [ ]:
# Additional Exercise

- For each movies extract the detailed information from IMDB, 
- Find out the embeddings of this detailed information
- Compute similarity matix between movies based on embeddings
- Observe if it makes sense?


In [ ]:
# Q:If there is new movies, can you find similar movies to it?
A: We can use the embeddings ...


In [ ]:
# Question: You need to build a place recommender how would you go about it?
User, Restaurent, rating
